# Referencias {-}

Fernández-Casal R., Costa J. y Oviedo de la Fuente, M. (2021). *[Aprendizaje Estadístico](https://rubenfcasal.github.io/aprendizaje_estadistico)*. [github](https://github.com/rubenfcasal/aprendizaje_estadistico).

Gil Bellosta C.J. (2018). *[R para profesionales de los datos: una introducción](https://www.datanalytics.com/libro_r/index.html)*.

Grolemund, G. (2014). *[Hands-on programming with R: Write your own functions and simulations](https://rstudio-education.github.io/hopr)*, [O'Reilly](http://shop.oreilly.com/product/0636920028574.do).

Matloff, N. (2011). *The art of R programming: A tour of statistical software design*, [No Starch Press](https://www.nostarch.com/artofr.htm).

Quintela del Rio A. (2019). *[Estadística Básica Edulcorada](https://bookdown.org/aquintela/EBE)*

Wickham, H., y Grolemund, G. (2016). *[R for data science: import, tidy, transform, visualize, and model data](http://r4ds.had.co.nz)*, [online-castellano](https://es.r4ds.hadley.nz), [O'Reilly](http://shop.oreilly.com/product/0636920034407.do).


## Enlaces {.unnumbered #links}

***Repositorio***: [rubenfcasal/intror](https://github.com/rubenfcasal/intror)

**Recursos para el aprendizaje de R**: En este [post](https://rubenfcasal.github.io/post/ayuda-y-recursos-para-el-aprendizaje-de-r) se muestran algunos recursos que pueden ser útiles para el aprendizaje de R y la obtención de ayuda.

[***Bookdown***](https://bookdown.org):

* Fernández-Casal, R. y Cotos-Yáñez, T.R. (2018). *[Escritura de libros con bookdown](https://rubenfcasal.github.io/bookdown_intro)*,   [github](https://github.com/rubenfcasal/bookdown_intro). Incluye un apéndice con una [Introducción a RMarkdown](https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html). 

* Kuhn, M. y Silge, J. (2022). *[Tidy Modeling with R](https://www.tmwr.org)*. [O'Reill](https://amzn.to/35Hn96s).

* Wickham, H. (2015). *[R packages: organize, test, document, and share your code](http://r-pkgs.had.co.nz/)* (actualmente 2ª edición en desarrollo con H. Bryan), [O'Reilly, 1ª edición](http://shop.oreilly.com/product/0636920034421.do).

* Wickham, H. (2019). *[Advanced R, 2ª edición](https://adv-r.hadley.nz/)*, [Chapman & Hall](https://www.amazon.com/dp/0815384572), [1ª edición.](http://adv-r.had.co.nz/).

[***Posit (RStudio)**](https://posit.co)

* [Blog](https://posit.co/blog)

* [Videos](https://posit.co/resources/videos)

* [Chuletas (Cheatsheets)](https://posit.co/resources/cheatsheets)

* [***tidyverse***](https://www.tidyverse.org/):

    - [dplyr](https://dplyr.tidyverse.org)
    
    - [tibble](https://tibble.tidyverse.org)
    
    - [tidyr](https://tidyr.tidyverse.org)
    
    - [stringr](https://stringr.tidyverse.org)
    
    - [readr](https://readr.tidyverse.org)
    
    - [Best Practices in Working with Databases](https://solutions.posit.co/connections/db)
    
* [tidymodels](https://www.tidymodels.org)    

* [sparklyr](https://spark.rstudio.com/)

* [shiny](http://shiny.rstudio.com)

## Bibliografía complementaria {-}

Beeley (2015). *Web Application Development with R Using Shiny*.
Packt Publishing.

Bivand *et al.* (2008). *Applied Spatial Data Analysis with R*. Springer.

James *et al.* (2008). *An Introduction to Statistical Learning: with
Aplications in R*. Springer.

Kolaczyk y Csárdi (2014). *Statistical analysis of network data with R*. Springer.

Munzert *et al.* (2014). *Automated Data Collection with R: 
A Practical Guide to Web Scraping and Text Mining*. Wiley.

Ramsay *et al.* (2009). *Functional Data Analysis with R and MATLAB*.
Springer.

Van der Loo y de Jonge (2012). *Learning RStudio for R Statistical
Computing*. Packt Publishing.

Williams (2011). *Data Mining with Rattle and R*. Springer.

Wood (2006). *Generalized Additive Models: An Introduction with R*. Chapman.

Yihui Xie (2015). *Dynamic Documents with R and knitr*. Chapman.



